export type ProductsType = {
  XX99Price: number;
  setXX99Price: React.Dispatch<React.SetStateAction<number>>;
  XX99qnty: number;
  setXX99qnty: React.Dispatch<React.SetStateAction<number>>;
  XX99IPrice: number;
  setXX99IPrice: React.Dispatch<React.SetStateAction<number>>;
  XX99Iqnty: number;
  setXXI99qnty: React.Dispatch<React.SetStateAction<number>>;
  XX59qnty: number;
  setXX59qnty: React.Dispatch<React.SetStateAction<number>>;
  XX59Price: number;
  setXX59Price: React.Dispatch<React.SetStateAction<number>>;
  ZX9Price: number;
  setZX9Price: React.Dispatch<React.SetStateAction<number>>;
  ZX9Qnty: number;
  setZX9Qnty: React.Dispatch<React.SetStateAction<number>>;
  ZX7Price: number;
  setZX7Price: React.Dispatch<React.SetStateAction<number>>;
  ZX7Qnty: number;
  setZX7Qnty: React.Dispatch<React.SetStateAction<number>>;
  YX1Price: number;
  YX1Qnty: number;
  setYX1Qnty: React.Dispatch<React.SetStateAction<number>>;
  setYX1Price: React.Dispatch<React.SetStateAction<number>>;
};
